# Generated by Django 5.0.3 on 2024-04-13 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reserve_Class", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("disponible", models.BooleanField(default=True)),
                ("capacidad", models.IntegerField()),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Registro",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="nivel",
        ),
        migrations.AddField(
            model_name="reserva",
            name="clase",
            field=models.CharField(default="valor_predeterminado", max_length=100),
        ),
        migrations.AddField(
            model_name="reserva",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reserva",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reserva",
            name="hora_fin",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reserva",
            name="hora_inicio",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
